packages/resolve-scripts/src/server/express.js
queryParameters.push(**JSON.parse**(req.query.variables));
=> Fix parse variables

packages/resolve-scripts/src/template/resolve.build.config.js, packages/resolve-scripts/src/template_empty/client/reducers/index.js, packages/resolve-scripts/src/template_empty/client/store/index.js, packages/resolve-scripts/src/template_empty/resolve.server.config.js
=> Fix resolve-scripts templates issues

packages/create-resolve-app/README.md, packages/create-resolve-app/bin/index.js, packages/resolve-scripts/src/template/README.md, packages/resolve-scripts/src/template/common/read-models/default/index.js
=> fix(create-resolve-app): Describe options in the documentation

packages/create-resolve-app/README.md, packages/resolve-scripts/src/scripts/init.js, packages/resolve-scripts/src/template/README.md, packages/resolve-scripts/src/template_empty/tests/e2e-tests/index.test.js, packages/resolve-scripts/src/template_empty/tests/testcafe_runner.js
=> fix(resolve-scripts): Add `TestCafe` and `Flow` to an empty application template

packages/resolve-scripts/package.json, packages/resolve-scripts/src/configs/server.config.js, packages/resolve-scripts/src/server/auth/githubStrategy.js, packages/resolve-scripts/src/server/auth/googleStrategy.js, packages/resolve-scripts/src/server/auth/localStrategy.js, packages/resolve-scripts/src/server/express.js, packages/resolve-scripts/src/template/README.md, packages/resolve-scripts/src/template/resolve.server.config.js, packages/resolve-scripts/src/template_sample/resolve.server.config.js
BREAKING CHANGE:
- `resolve.server.config.js` - function `extendExpress` is deprecated
=> docs(resolve-scripts): fix documentation for server config - `auth` section

README.md, docs/View Models.md, examples/README.md, examples/todo/README.md, packages/README.md, packages/bus-adapters/README.md, packages/bus-adapters/resolve-bus-memory/README.md, packages/bus-adapters/resolve-bus-rabbitmq/README.md, packages/bus-adapters/resolve-bus-zmq/README.md, packages/create-resolve-app/README.md, packages/readmodel-adapters/README.md, packages/readmodel-adapters/resolve-readmodel-memory/README.md, packages/readmodel-adapters/resolve-readmodel-mongo/README.md, packages/readmodel-adapters/resolve-readmodel-redis/README.md, packages/resolve-command/README.md, packages/resolve-es/README.md, packages/resolve-query/README.md, packages/resolve-redux/README.md, packages/resolve-scripts/README.md, packages/resolve-scripts/src/template/README.md, packages/storage-adapters/README.md, packages/storage-adapters/resolve-storage-lite/README.md, packages/storage-adapters/resolve-storage-mongo/README.md
=> docs(all packages): fix links

packages/storage-adapters/resolve-storage-base/src/concurrent_error.js, packages/storage-adapters/resolve-storage-lite/src/storage.js
=> fix(resolve-storage-lite): error message

packages/resolve-redux/README.md
https://github.com/reimagined/resolve/issues/534
=> Hotfix/Resolve-redux docs (#534 issue)

new-readme.md
=> New readme

README.md, docs/Tutorials/Hacker News Tutorial.md, docs/Tutorials/ToDo List App Tutorial.md
* First draft of new readme
* Add text to examples description
* Add get in touch text
* Add compatibility
* Add footer
* Add examples text
* Add documention part
* New readme (#544)
* Change images (from designer)
* Add hacker-news to readme
* New button
* New readme [2] (#548)
* Actualize new readme
* Prepare to make the new readme
* Add new readme
=> Feature/new readme (#571)

packages/resolve-scripts/src/runtime/client/index.js, packages/resolve-scripts/src/runtime/server/get_html_markup.js
https://github.com/Microsoft/reactxp/blob/feaed8d733d84f16a87b1eb91300b8e666e7c8b7/src/web/FrontLayerViewManager.tsx#L190
=> Hot fix for support reactxp

packages/readmodel-adapters/resolve-readmodel-base/src/build-projection.js, packages/readmodel-adapters/resolve-readmodel-base/src/init.js, packages/readmodel-adapters/resolve-readmodel-base/test/build-projection.tests.js, packages/readmodel-adapters/resolve-readmodel-base/test/init.tests.js, packages/readmodel-adapters/resolve-readmodel-mysql/src/implementation.js, packages/readmodel-adapters/resolve-readmodel-mysql/test/store-api.tests.js, packages/resolve-query/README.md, packages/resolve-query/src/read-model.js, packages/resolve-query/test/read-model.tests.js, packages/resolve-scripts/src/runtime/server/read_model_non_reactive_handler.js, packages/resolve-scripts/src/runtime/server/read_model_query_executors.js, packages/resolve-scripts/src/runtime/server/read_model_reactive_handler.js
PR closes #607 and closes #612
=> Improve read models error handling

README.md
=> New README review

packages/README.md, packages/adapters/README.md, packages/adapters/subscribe-adapters/README.md, packages/core/README.md, tests/README.md
Review of the https://github.com/reimagined/resolve/pull/705
=> [Review] Feature/prepare repo structure

docs/Server HTTP API.md
=> Docs/Server HTTP API article

packages/core/resolve-scripts/src/core/alias/$resolve.viewModels.js, packages/core/resolve-scripts/test/alias/__snapshots__/$resolve.viewModels.test.js.snap
Fix view-model projection function classifier check for custom babelification in customer application
=> Prepare to V0.15.2

.eslintrc.js, examples/shopping-list/common/aggregates/shopping_list.commands.js, examples/shopping-list/common/read-models/shopping_lists.projection.js, examples/shopping-list/common/read-models/shopping_lists.resolvers.js, examples/shopping-list/package.json, examples/shopping-list/test/unit/aggregates.test.js, examples/shopping-list/test/unit/read_models.test.js, packages/core/create-resolve-app/src/create_resolve_app.js, packages/core/resolve-testing-tools/.npmignore, packages/core/resolve-testing-tools/.yarnrc, packages/core/resolve-testing-tools/README.md, packages/core/resolve-testing-tools/package.json, packages/core/resolve-testing-tools/src/apply-event.js, packages/core/resolve-testing-tools/src/apply-events.js, packages/core/resolve-testing-tools/src/create-read-model.js, packages/core/resolve-testing-tools/src/create-resolver.js, packages/core/resolve-testing-tools/src/create-resolvers.js, packages/core/resolve-testing-tools/src/index.js, packages/core/resolve-testing-tools/test/apply-event.test.js, packages/core/resolve-testing-tools/test/apply-events.test.js, packages/core/resolve-testing-tools/test/create-read-model.test.js, packages/core/resolve-testing-tools/test/create-resolver.test.js, packages/core/resolve-testing-tools/test/create-resolvers.test.js, packages/core/resolve-testing-tools/test/index.test.js, yarn.lock
* Add package "resolve-testing-tools"
```js
import { createReadModel } from 'resolve-testing-tools'
import projection from './common/read-models/something.projection'
import resolvers from './common/read-models/something.resolvers'
describe('read-model "something"', () => {
let readModel
beforeEach(() => {
readModel = createReadModel({
name: 'something', 
projection, 
resolvers, 
/* adapter */ // custom adapter 
}) 
})
afterEach(async () => {
await readModel.dispose()
})
test('resolver "myCustomResolverName" should return correctly result', async () => {   
await readModel.applyEvent(event)
await readModel.applyEvents(events)
const result = await readModel.resolvers.myCustomResolverName(resolverArgs, jwtToken)
expect(result).toMatchSnapshot()
})
})
```
=> Prepare to 0.17.4

packages/core/resolve-runtime/src/cloud_entry.js
=> Fix event loop problems

packages/core/resolve-scripts/src/get_modules_dirs.js, packages/core/resolve-scripts/src/get_monorepo_node_modules.js, packages/core/resolve-scripts/src/resolve_file.js
=> Fix find node_modules

examples/hacker-news/package.json, examples/hello-world/package.json, examples/shopping-list-advanced/scripts/install.js, examples/shopping-list-advanced/web/package.json, examples/shopping-list/package.json, examples/with-postcss/package.json, examples/with-saga/package.json, examples/with-styled-components/package.json, packages/adapters/storage-adapters/resolve-storage-dynamo/src/create-query.js, packages/adapters/storage-adapters/resolve-storage-dynamo/test/__snapshots__/create-query.test.js.snap, packages/adapters/storage-adapters/resolve-storage-dynamo/test/create-query.test.js, packages/modules/resolve-module-auth/src/index.js, yarn.lock
* Fix Redux DevTools
* Fix "install" in "shopping-list-advanced"
* Fix wildcard in "resolve-storage-dynamo" 
* Optional "logoutRoute" in "resolve-module-auth"
=> Many fixes

packages/core/resolve-command/src/index.js, packages/core/resolve-command/test/index.test.js, packages/core/resolve-es/src/index.js, packages/core/resolve-es/test/index.test.js
Monotonically increasing timestamp on command by aggregateId
Fix #914
=> Monotonically increasing timestamp on command by aggregateId

packages/adapters/api-handler-adapters/resolve-api-handler-awslambda/src/index.js, packages/modules/resolve-module-auth/src/send_auth_response.js
Fix auth strategy error passing into response
Fix #921
=> Fix auth strategy error passing into response

packages/core/resolve-scripts/src/resolve_relative_path.js, packages/modules/resolve-module-auth/src/authenticate_wrapper.js, packages/modules/resolve-module-auth/test/authenticate_wrapper.test.js
Improve error handling in resolve-module-auth
=> Improve error handling in resolve-module-auth

examples/shopping-list-advanced/README.md, examples/shopping-list-advanced/package.json, examples/shopping-list-advanced/web/run.js, packages/core/resolve-scripts/src/adjust_webpack_common_packages.js, packages/core/resolve-scripts/src/adjust_webpack_react_native.js, packages/core/resolve-scripts/src/index.js
Split adjustWebpackReactNative/adjustWebpackCommonPackages
=> Split adjustWebpackReactNative/adjustWebpackCommonPackages

examples/hello-world/config.dev.js, examples/hello-world/config.prod.js, packages/adapters/snapshot-adapters/resolve-snapshot-lite/README.md, packages/adapters/snapshot-adapters/resolve-snapshot-mysql/README.md, packages/core/resolve-es/README.md
=> Improve adapters docs

packages/adapters/readmodel-adapters/resolve-readmodel-mongo/src/meta-api.js, packages/modules/resolve-module-auth/src/wrap_auth_request.js, packages/modules/resolve-module-auth/test/wrap_auth_request.test.js
=> Fix "resolve-module-auth" 

packages/adapters/api-handler-adapters/resolve-api-handler-awslambda/src/index.js, packages/adapters/api-handler-adapters/resolve-api-handler-awslambda/test/__snapshots__/index.test.js.snap, packages/adapters/api-handler-adapters/resolve-api-handler-awslambda/test/index.test.js, packages/adapters/api-handler-adapters/resolve-api-handler-express/src/index.js, packages/adapters/api-handler-adapters/resolve-api-handler-express/test/__snapshots__/index.test.js.snap, packages/adapters/api-handler-adapters/resolve-api-handler-express/test/index.test.js
=> Fix #926 / Fix #927

packages/adapters/readmodel-adapters/resolve-readmodel-base/src/wait-event-causal-consistency.js
=> Implement wait for read-model Init first invokation

packages/modules/resolve-module-comments/src/common/read-models/comments.resolvers.js
=> Fix first missing comment in comments module at pagination view

packages/core/resolve-redux/src/connect_view_model.js, packages/core/resolve-redux/test/connect_view_model.test.js
=> AggregateIds validation in resolve-redux connector

packages/core/resolve-scripts/src/alias/$resolve.seedClientEnvs.js
https://github.com/reimagined/resolve-cloud/issues/22
=> Use log instead of warn to put logs to stdout instead of stderr

packages/adapters/readmodel-adapters/resolve-readmodel-mongo/src/__mocks__/mongodb.js, packages/adapters/readmodel-adapters/resolve-readmodel-mongo/src/connect.js, packages/adapters/readmodel-adapters/resolve-readmodel-mongo/src/define-table.js, packages/adapters/readmodel-adapters/resolve-readmodel-mongo/src/list-read-model-tables.js, packages/adapters/readmodel-adapters/resolve-readmodel-mongo/test/__snapshots__/index.test.js.snap, yarn.lock
=> Fix mongodb BC / Cache listReadmodelTables

packages/core/resolve-runtime/src/local/query-is-ready-handler.js, packages/core/resolve-scripts/src/generate_custom_mode.js, packages/core/resolve-scripts/src/run_testcafe.js
=> Refactor run-testcafe mode to custom mode

packages/modules/resolve-module-admin/README.md, packages/modules/resolve-module-admin/src/api-handlers/event-broker-pause.js, packages/modules/resolve-module-admin/src/api-handlers/event-broker-reset.js, packages/modules/resolve-module-admin/src/api-handlers/event-broker-resume.js, packages/modules/resolve-module-admin/src/api-handlers/event-broker-set-property.js, packages/modules/resolve-module-admin/src/commands/sagas/properties/list.js, packages/modules/resolve-module-admin/src/commands/sagas/reset.js, packages/modules/resolve-module-admin/src/commands/sagas/resume.js
Add flag --side-effects-start-timestamp #1248.
=> Add flag to resolve-module-admin

website/pages/en/index.js
**I found a typo, JavaScript is always written as a single word.**
https://en.wikipedia.org/wiki/JavaScript
=> Java Script -> Javascript

packages/adapters/eventstore-adapters/resolve-eventstore-lite/tsconfig.json, packages/adapters/eventstore-adapters/resolve-eventstore-mysql/tsconfig.json, packages/adapters/eventstore-adapters/resolve-eventstore-postgresql-serverless/tsconfig.json, packages/adapters/eventstore-adapters/resolve-eventstore-postgresql/tsconfig.json, packages/core/resolve-client/tsconfig.json, packages/core/resolve-react-hooks/tsconfig.json, packages/internal/babel-compile/bin/index.js, packages/internal/babel-compile/bin/prepare.js, packages/internal/babel-compile/package.json, packages/internal/helpers/get-compile-configs.js, yarn.lock
=> Improve "build"

examples/personal-data/client/components/ProfileWithViewModel.js, examples/personal-data/common/encryption-factory.js, examples/personal-data/config.dev.js, examples/personal-data/package.json, yarn.lock
Cryptr uses crypto nodejs module which browserify implementation very slow
=> Personal data example profile update page freezes on opening

packages/core/resolve-testing-tools/src/as.ts, packages/core/resolve-testing-tools/src/command.ts, packages/core/resolve-testing-tools/src/given-events.ts, packages/core/resolve-testing-tools/src/index.ts, packages/core/resolve-testing-tools/src/read-model.ts, packages/core/resolve-testing-tools/src/saga.ts
Add typings for 
givenEvents([]) function
and for 
as, readModel, saga, properties, command, aggregate, shouldThrow and shouldProduceEvent methods
=> Fixture/Typings for given-events

packages/adapters/eventstore-adapters/resolve-eventstore-postgresql-serverless/src/js/load-events-by-timestamp.js, packages/adapters/eventstore-adapters/resolve-eventstore-postgresql-serverless/test/load-events-by-timestamp.test.ts, packages/adapters/eventstore-adapters/resolve-eventstore-postgresql/src/js/load-events-by-timestamp.js, packages/adapters/eventstore-adapters/resolve-eventstore-postgresql/test/load-events-by-timestamp.test.ts
=> Fix typo / Add unit-tests

packages/adapters/eventstore-adapters/resolve-eventstore-base/src/export.ts, packages/adapters/eventstore-adapters/resolve-eventstore-base/src/import.ts, packages/adapters/eventstore-adapters/resolve-eventstore-base/src/index.ts, packages/adapters/eventstore-adapters/resolve-eventstore-base/src/types.ts
Type declarations for eventstore adapters `import` and `export`
=> Types for import and export from eventstore adapter

packages/runtime/adapters/eventstore-adapters/eventstore-base/src/get-next-cursor.ts, packages/runtime/adapters/eventstore-adapters/eventstore-base/src/index.ts, packages/runtime/adapters/eventstore-adapters/eventstore-base/src/types.ts, packages/runtime/adapters/readmodel-adapters/readmodel-base/package.json, packages/runtime/adapters/readmodel-adapters/readmodel-base/src/types.ts, packages/runtime/adapters/readmodel-adapters/readmodel-mysql/src/build.ts, packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/build.ts
Also fixed `eventsSizeLimit` parameter name in filter type
=> Deduplicate eventstore-related types re-declared in readmodel adapter

examples/hacker-news/import/api.js, examples/hacker-news/import/import_secret_api_handler.js, examples/hacker-news/import/importer.js, examples/hacker-news/run.js
=> Generate secrets in hacker-news import

packages/modules/module-admin/src/api-handlers/event-broker-read-models-list.js, packages/modules/module-admin/src/api-handlers/event-broker-sagas-list.js, packages/modules/module-admin/src/api-handlers/wrap-api-handler.js, packages/modules/module-admin/src/commands/read-models/list.js, packages/modules/module-admin/src/commands/sagas/list.js, packages/modules/module-admin/src/utils/getEventDate.js, packages/modules/module-admin/test/__snapshots__/index.test.js.snap, packages/modules/module-admin/test/api-handlers.test.js, packages/modules/module-admin/test/index.test.js, packages/runtime/runtime/src/common/query/wrap-read-model.ts, packages/runtime/runtime/test/wrap-read-model.test.ts
=> Fix module-admin

packages/tools/testing-tools/src/flow/read-model/make-test-environment.ts, packages/tools/testing-tools/src/flow/saga/make-test-environment.ts, tests/read-model-store-api/count.test.js, tests/read-model-store-api/resolvers.js
=> Fix testing-tools (over 100 events)

packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/src/load-events-by-cursor.ts, packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/test/load-events-by-cursor.test.ts, tests/eventstore-order-events/index.test.ts, tests/package.json
=> Fix order of events in postgres-serverless eventstore adapter

packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/delete-secret.ts, packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/save-event.ts, packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/set-secret.ts, tests/eventstore-parallel-save/index.test.ts, tests/package.json
=> Fix #1886 - parallel write in sqlite eventstore adapter

packages/core/client/package.json, packages/core/client/src/subscribe-adapter.ts, packages/core/client/test/unit/subscription-adapter.unit.test.ts, packages/runtime/runtime/src/cloud/index.js, packages/runtime/runtime/src/cloud/websocket-event-handler.js, packages/runtime/runtime/src/local/create-pubsub-manager.js, packages/runtime/runtime/src/local/init-websockets.js, yarn.lock
=> Fix duplicated events in view-model subscriptions

examples/ts/hacker-news/config.dev.replica.ts, examples/ts/hacker-news/config.prod.ts, packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/save-event.ts, tests/eventstore-parallel-save/index.test.ts, tests/eventstore-save-load/index.test.ts
saveEvent can stuck if too many parallel async operations try to write to the database
=> Fix sqlite saveEvent

packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/get-cursor-until-event-types.ts, packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/replicate-events.ts, packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/save-event.ts, tests/eventstore-replication/index.test.ts, tests/eventstore-save-load/index.test.ts, yarn.lock
Explicitly convert and check the result of some postgresql queries
=> Improve tests to handle possible errors on big number of events.

packages/tools/scripts/configs/schema.resolve.config.json, packages/tools/scripts/test/config.test.js
=> Fix config validation warnings on app startup

packages/runtime/adapters/readmodel-adapters/readmodel-base/src/already-disposed-error.ts, packages/runtime/adapters/readmodel-adapters/readmodel-base/src/create-adapter-factory.ts, packages/runtime/adapters/readmodel-adapters/readmodel-base/src/create-adapter.ts, packages/runtime/adapters/readmodel-adapters/readmodel-base/src/index.ts, packages/runtime/adapters/readmodel-adapters/readmodel-base/src/types.ts, packages/runtime/adapters/readmodel-adapters/readmodel-base/src/wrap-disconnect.ts, packages/runtime/adapters/readmodel-adapters/readmodel-base/src/wrap-operation.ts, packages/runtime/adapters/readmodel-adapters/readmodel-base/test/index.test.ts, packages/runtime/runtimes/runtime-base/src/create-runtime.ts
Fixes https://github.com/reimagined/resolve/issues/2101
=> Improve already dispose error handling for all disposable resolve resoures, inclusing read-model adapters

examples/ts/shopping-list/README.md, packages/tools/scripts/src/validate_config.js, packages/tools/scripts/test/config.test.js, templates/ts/react/run.ts
=> Fix api handler path validation

tests/eventstore-secrets/index.test.ts
```
[mdis]:# (./eventstore-secrets/index.test.ts#set-secret)
\```js
await secretManager.setSecret(id, secret)
\```
[mdis]:# (./eventstore-secrets/index.test.ts#delete-secret)
\```js
const isDeleted = await secretManager.deleteSecret(id)
\```
[mdis]:# (./eventstore-secrets/index.test.ts#get-secret)
\```js
const secret = await secretManager.getSecret(id)
\```
```
=> Code Samples for SecretManager
